version: '3.1'
services:
  security-postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: security
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: USERS
    ports:
      - "5433:5432"
    volumes:
      - dataFinTechSecure:/var/lib/postgresql/data
    networks:
      - finTech

  bank-redis:
    image: docker.io/bitnami/redis
    container_name: redis_bank
    ports:
      - "6380:6379"
    environment:
      - REDIS_PASSWORD=redis_bank_pass
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - redis-bank-data:/bitnami/redis/data
    networks:
      - finTech
volumes:
  dataFinTechSecure: {}
  redis-bank-data: {}
networks:
  finTech:
    driver: bridge