version: '3.1'
services:
  security-postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: security
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: USERS
    ports:
      - "5433:5432"
    volumes:
      - dataFinTechSecure:/var/lib/postgresql/data
    networks:
      - finTech

volumes:
  dataFinTechSecure: {}
networks:
  finTech:
   driver: bridge